#!/usr/bin/env python3
"""Tables for the externalization report (SPEC.md "Analysis and figures" +
approved amendments). Writes one markdown file.

  python3 scripts/make_tables.py                              # real results
  python3 scripts/make_tables.py --results-dir <fixture> \
      --levels-json <fixture>/levels.json --out <fixture>/tables.md

Tables:
 1. Pooled logistic robustness check: majority-solved ~ logB + log difficulty
    + interaction (hand-rolled Newton MLE; statsmodels not installed), with
    implied B*(difficulty) at each bin median vs the binned logistic B*.
 2. Selectivity battery: MMLU / SST-2, clean vs medium ablation.
 3. Faithfulness spot check: full vs 50%-truncated-trace accuracy, base vs
    medium ablation (prediction 4).
 4. Verbosity confound at B = 16384 (amendment 7): think-token usage and
    truncation rates, ablated vs base.
 5. Difficulty-definition sensitivity (amendment 7): median-over-successes vs
    median-over-all-Pile-B; problems changing bins on rebinning.
 6. MATH-level vs difficulty-proxy cross-check; GSM8K vs MATH retention at
    matched difficulty.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from collections import defaultdict

import numpy as np
from scipy.special import expit
from scipy.stats import norm, spearmanr

from extcot import analysis

B_MAX = 16384
BUDGETS = [0, 128, 512, 2048, 16384]
LEVEL_TAGS = [("light", "jspace-light"), ("medium", "jspace-med"),
              ("heavy", "jspace-heavy"), ("random-s0", "random-s0"),
              ("random-s1", "random-s1")]


def load_runs(rd, tag):
    path = os.path.join(rd, "runs", f"{tag}.jsonl")
    if not os.path.exists(path):
        print(f"  WARN: missing {tag}, skipping")
        return None
    rows = []
    with open(path) as f:
        for line in f:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return rows


def collect_outcomes(rd, prefix, budgets=BUDGETS):
    out = {}
    for B in budgets:
        rows = load_runs(rd, f"{prefix}-B{B}")
        if rows:
            out[B] = analysis.majority(rows)
    return out


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    w = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return (max(0, c - w), min(1, c + w))


def fit_pooled_logistic(X, y, ridge=1e-6):
    """Newton-Raphson MLE for y ~ Bernoulli(expit(X beta)). Returns beta, SE."""
    X = np.asarray(X, float)
    y = np.asarray(y, float)
    beta = np.zeros(X.shape[1])
    for _ in range(60):
        p = expit(X @ beta).clip(1e-9, 1 - 1e-9)
        g = X.T @ (y - p) - ridge * beta
        H = (X * (p * (1 - p))[:, None]).T @ X + ridge * np.eye(X.shape[1])
        step = np.linalg.solve(H, g)
        beta = beta + step
        if np.abs(step).max() < 1e-9:
            break
    cov = np.linalg.inv(H)
    return beta, np.sqrt(np.diag(cov))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", default="/workspace/jlens-cot/results")
    ap.add_argument("--out", default=None, help="default <results-dir>/tables.md")
    ap.add_argument("--levels-json", default=None,
                    help="{pid: MATH level}; default: extcot.data.load_problems()")
    args = ap.parse_args()
    rd = args.results_dir.rstrip("/")
    out_path = args.out or os.path.join(rd, "tables.md")

    design = json.load(open(os.path.join(rd, "design.json")))
    problems = design["problems"]
    edges = design["bin_edges"]
    in_sample = {pid: p for pid, p in problems.items()
                 if p.get("in_sample", p["included"])}

    md = ["# Analysis tables (auto-generated by scripts/make_tables.py)", ""]

    # ---------------------------------------------- 1. pooled logistic
    md += ["## 1. Pooled logistic robustness check",
           "",
           "Per-problem majority outcome ~ `b0 + b1*log(B+1) + b2*log(d) + "
           "b3*log(B+1)*log(d)` (Newton MLE, Wald SEs). Positive `b1`, negative "
           "`b2`, and the implied B*(d) reproducing the binned fit support the "
           "binned estimator.",
           "",
           "| series | b0 | b1 (logB) | b2 (log d) | b3 (interact) | n |",
           "|---|---|---|---|---|---|"]
    pooled_fits = {}
    outcomes_by_series = {}
    for name, prefix in LEVEL_TAGS:
        oc = collect_outcomes(rd, prefix)
        if not oc:
            continue
        outcomes_by_series[name] = oc
        X, y = [], []
        for B, by_pid in oc.items():
            for pid, solved in by_pid.items():
                if pid not in in_sample:
                    continue
                lb, ld = math.log(B + 1), math.log(in_sample[pid]["difficulty"])
                X.append([1.0, lb, ld, lb * ld])
                y.append(solved)
        beta, se = fit_pooled_logistic(X, y)
        pooled_fits[name] = beta
        cells = " | ".join(f"{b:.3f} ({s:.3f})" for b, s in zip(beta, se))
        md.append(f"| {name} | {cells} | {len(y)} |")
    md += ["", "Implied B* at bin median difficulty (pooled model, target = "
           "0.9 x bin base rate) vs binned logistic B* (analysis.cell_bstar):",
           "",
           "| series | bin | median d | binned B* | pooled B* |",
           "|---|---|---|---|---|"]
    for name, prefix in LEVEL_TAGS:
        if name not in outcomes_by_series:
            continue
        res = analysis.cell_bstar(problems, outcomes_by_series[name], edges,
                                  n_boot=0)
        beta = pooled_fits[name]
        for b, v in sorted(res.items()):
            d = v["median_difficulty"]
            target = 0.9 * v["base_rate"]
            ld = math.log(d)
            slope = beta[1] + beta[3] * ld
            if slope <= 1e-9:
                pooled = "n/a (slope<=0)"
            else:
                x = (math.log(target / (1 - target)) - beta[0] - beta[2] * ld) / slope
                Bp = math.exp(x) - 1
                pooled = ("<=0" if Bp < 0 else
                          f"CENSORED (> {B_MAX})" if Bp > B_MAX else f"{Bp:.0f}")
            binned = "CENSORED" if v["censored"] else f"{v['bstar']:.0f}"
            md.append(f"| {name} | {b} | {d:.0f} | {binned} | {pooled} |")
    md.append("")

    # ---------------------------------------------- 2. selectivity
    md += ["## 2. Selectivity battery (MMLU / SST-2, direct answering, B=0)",
           "",
           "| dataset | clean acc | medium-ablation acc | delta | note |",
           "|---|---|---|---|---|"]
    sel = {}
    for tag in ("select-clean", "select-med"):
        rows = load_runs(rd, tag)
        if rows:
            for ds in ("mmlu", "sst2"):
                sub = [r["solved"] for r in rows if r["dataset"] == ds]
                if sub:
                    sel[(tag, ds)] = (sum(sub), len(sub))
    for ds in ("mmlu", "sst2"):
        if ("select-clean", ds) in sel and ("select-med", ds) in sel:
            kc, nc = sel[("select-clean", ds)]
            km, nm = sel[("select-med", ds)]
            lo, hi = wilson(km, nm)
            note = ("within noise of clean" if lo <= kc / nc <= hi
                    else "OUTSIDE clean CI - check")
            md.append(f"| {ds} | {kc/nc:.3f} ({kc}/{nc}) | {km/nm:.3f} "
                      f"({km}/{nm}, 95% CI {lo:.3f}-{hi:.3f}) | "
                      f"{km/nm - kc/nc:+.3f} | {note} |")
    md.append("")

    # ---------------------------------------------- 3. faithfulness
    md += ["## 3. Faithfulness spot check (traces truncated at 50%)",
           "",
           "| condition | n | full-trace acc | truncated acc | drop | "
           "solved->unsolved |",
           "|---|---|---|---|---|---|"]
    drops = {}
    for label, tag in [("base", "faith-clean-f0.5"),
                       ("medium ablation", "faith-jspace-med-B16384-f0.5")]:
        rows = load_runs(rd, tag)
        if not rows:
            continue
        n = len(rows)
        full = sum(r["orig_solved"] for r in rows)
        trunc = sum(r["solved"] for r in rows)
        flips = sum(1 for r in rows if r["orig_solved"] and not r["solved"])
        drops[label] = full / n - trunc / n
        md.append(f"| {label} | {n} | {full/n:.3f} | {trunc/n:.3f} | "
                  f"{full/n - trunc/n:.3f} | {flips} |")
    if len(drops) == 2:
        d_ab, d_b = drops["medium ablation"], drops["base"]
        md += ["", f"Truncation hurts the ablated model more by "
               f"**{d_ab - d_b:+.3f}** (prediction 4 expects > 0)."]
    md.append("")

    # ---------------------------------------------- 4. verbosity confound
    md += ["## 4. Verbosity confound at B = 16384 (amendment 7)",
           "",
           "Think-token usage on the solvable set. If usage saturates near the "
           "cap, measured B* is bounded by verbosity, not ability (SPEC caveat).",
           "",
           "| condition | n rows | mean think | median think | p90 think | "
           "frac truncated | frac > 0.9*cap |",
           "|---|---|---|---|---|---|---|"]
    clean_rows = load_runs(rd, "clean") or []
    base_b = [r for r in clean_rows
              if r["sample_idx"] >= 4 and r["pid"] in in_sample]
    conds = [("base (clean Pile B)", base_b)]
    for label, tag in [("light", "jspace-light-B16384"),
                       ("medium", "jspace-med-B16384"),
                       ("heavy", "jspace-heavy-B16384"),
                       ("random-s0", "random-s0-B16384"),
                       ("random-s1", "random-s1-B16384"),
                       ("out-of-band", "oob-B16384")]:
        rows = load_runs(rd, tag)
        if rows:
            conds.append((label, [r for r in rows if r["pid"] in in_sample]))
    for label, rows in conds:
        if not rows:
            continue
        t = np.array([r["think_tokens"] for r in rows], float)
        tr = np.mean([bool(r.get("truncated")) for r in rows])
        sat = np.mean(t >= 0.9 * B_MAX)
        md.append(f"| {label} | {len(rows)} | {t.mean():.0f} | "
                  f"{np.median(t):.0f} | {np.percentile(t, 90):.0f} | "
                  f"{tr:.3f} | {sat:.3f} |")
    md.append("")

    # ---------------------------------------------- 5. difficulty sensitivity
    md += ["## 5. Difficulty definition sensitivity (amendment 7)",
           "",
           "Primary difficulty = median think tokens over Pile-B *successes* "
           "(fallback: over all Pile B when no success). Alternative = median "
           "over ALL Pile-B attempts (`difficulty_all_b`). Rebinning with the "
           "same edges:", ""]
    inc = {pid: p for pid, p in problems.items() if p["included"]}
    changed, moves = 0, defaultdict(int)
    for pid, p in inc.items():
        b1 = analysis.bin_of(p["difficulty"], edges)
        b2 = analysis.bin_of(p["difficulty_all_b"], edges)
        if b1 != b2:
            changed += 1
            moves[(b1, b2)] += 1
    n_fb = sum(p.get("difficulty_fallback", False) for p in inc.values())
    md += [f"- Problems changing bins: **{changed}/{len(inc)} "
           f"({changed/len(inc):.1%})** of included problems.",
           f"- Problems using the fallback definition (no Pile-B success): "
           f"{n_fb}.",
           f"- Largest migrations: " + (", ".join(
               f"bin {a}->bin {b}: {n}" for (a, b), n in
               sorted(moves.items(), key=lambda kv: -kv[1])[:5]) or "none"),
           "", "| bin | n (successes-median) | n (all-B median) | "
           "bin median d (succ) | bin median d (all-B) |", "|---|---|---|---|---|"]
    for b in range(len(edges) - 1):
        m1 = [p["difficulty"] for p in inc.values()
              if analysis.bin_of(p["difficulty"], edges) == b]
        m2 = [p["difficulty_all_b"] for p in inc.values()
              if analysis.bin_of(p["difficulty_all_b"], edges) == b]
        md.append(f"| {b} | {len(m1)} | {len(m2)} | "
                  f"{np.median(m1):.0f} | {np.median(m2):.0f} |"
                  if m1 and m2 else f"| {b} | {len(m1)} | {len(m2)} | - | - |")
    md.append("")

    # ---------------------------------------------- 6. MATH level cross-check
    md += ["## 6. Difficulty proxy vs MATH level annotations", ""]
    levels = {}
    if args.levels_json:
        levels = {k: v for k, v in json.load(open(args.levels_json)).items()}
    else:
        try:
            from extcot.data import load_problems
            levels = {p["id"]: p["level"] for p in load_problems()
                      if p.get("level") is not None}
        except Exception as e:
            md.append(f"(MATH levels unavailable: {e})")
    if levels:
        md += ["| MATH level | n included | median difficulty | IQR |",
               "|---|---|---|---|"]
        pairs = []
        for lvl in sorted(set(levels.values())):
            ds = [p["difficulty"] for pid, p in inc.items()
                  if levels.get(pid) == lvl]
            pairs += [(lvl, d) for d in ds]
            if ds:
                md.append(f"| {lvl} | {len(ds)} | {np.median(ds):.0f} | "
                          f"{np.percentile(ds, 25):.0f}-"
                          f"{np.percentile(ds, 75):.0f} |")
        if pairs:
            rho, pv = spearmanr([a for a, _ in pairs], [b for _, b in pairs])
            md += ["", f"Spearman rho(level, difficulty) = **{rho:.3f}** "
                   f"(p = {pv:.2g}, n = {len(pairs)})."]
    md += ["", "GSM8K vs MATH at matched token difficulty: retention at "
           "B = 16384 under medium ablation, per shared bin (>= 8 problems "
           "each):", "",
           "| bin | GSM8K n | GSM8K retention | MATH n | MATH retention |",
           "|---|---|---|---|---|"]
    oc_med = outcomes_by_series.get("medium", {})
    top = oc_med.get(B_MAX, {})
    for b in range(len(edges) - 1):
        row = {}
        for ds in ("gsm8k", "math"):
            pids = [pid for pid, p in in_sample.items()
                    if p["dataset"] == ds and pid in top
                    and analysis.bin_of(p["difficulty"], edges) == b]
            if len(pids) >= 8:
                den = np.mean([in_sample[pid]["base_solved"] for pid in pids])
                row[ds] = (len(pids),
                           np.mean([top[pid] for pid in pids]) / den
                           if den > 0 else float("nan"))
        if len(row) == 2:
            md.append(f"| {b} | {row['gsm8k'][0]} | {row['gsm8k'][1]:.3f} | "
                      f"{row['math'][0]} | {row['math'][1]:.3f} |")
    md.append("")

    text = "\n".join(md)
    with open(out_path, "w") as f:
        f.write(text)
    print(text)
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
